ecommerce_product
    col.col-lg-6
        ecommerce_product_desc_and_reviews
        /ecommerce_product_desc_and_reviews
        ecommerce_product_price
        /ecommerce_product_price
        ecommerce_product_title
        /ecommerce_product_title
    /col
    col.col-lg-6
        ecommerce_product_gallery
        /ecommerce_product_gallery
    /col
/ecommerce_product