ecommerce_sidebar
	col.col-lg-12
		ecommerce_account_login
		/ecommerce_account_login
		ecommerce_category_list
		/ecommerce_category_list
		ecommerce_category_sorting
		/ecommerce_category_sorting
		ecommerce_product_featured_products
		/ecommerce_product_featured_products
	/col
/ecommerce_sidebar